### ISSUE TITLE
[REQUEST] Guide to setup Rest Api Server

### ISSUE THREAD

**Issue by kimjiwongit** [tsnanh/VKURESTfulService#1]
I am an Android Developer. I want to test the Android App.

Can you please add a README or write below how to setup the nodejs express server with detailed steps?

Thank you.

**Comment by tsnanh** [comment]
I'm using Google Cloud VM instance now :D.
Clone the app, send me SHA-1 and you are ready for testing

**Comment by kimjiwongit** [comment]
Can I run it locally with localhost? If yes, can you please send me details on how to setup locally?

It would be better for me to have it work locally. Thank you.

**Comment by tsnanh** [comment]
Yeah, you can! But currently i don't know how to write it :D. I'll add README as soon as possible. Can you wait for it?

**Comment by kimjiwongit** [comment]
Yes! I would really appreciate the README to setup the server! Thank you.

**Comment by tsnanh** [comment]
I am still learning and my code is so bad. I would be very grateful to you if you could share your experience with me. Thanks for paying attention to my repository :D and sorry for my bad English.

**Comment by kimjiwongit** [comment]
For backend. I don't know much. I am an Android Dev, still learning. I liked your tech stack so I wanted to tested your app!

**Comment by tsnanh** [comment]
I am very happy to have an Android developer test my application! Thank you❤

**Comment by tsnanh** [comment]
I just updated the README file. You should test and run it on your localhost. If you have any issue, please comment. :D

**Comment by kimjiwongit** [comment]
When running `npm start` I get the belowmessage. I expected the localhost to start but it does not.

```
 > sict-forum@0.0.0 start H:\PROJECTS\forks\javascript\javascript_forks\github\tsnanh\new\VKURESTfulService
> if [$NODE_ENV == 'production']; then node ./bin/www; else nodemon ./bin/www; fi
```

Can you please help?

**Comment by kimjiwongit** [comment]
![15874474024207487762197649132598](https://user-images.githubusercontent.com/62508267/79829281-4272ca00-83c0-11ea-951b-22012d1a510a.jpg)

**Comment by tsnanh** [comment]
Change 
if [$NODE_ENV == 'production']; then node ./bin/www; else nodemon ./bin/www; fi
to
node ./bin/www
It should work.

**Comment by kimjiwongit** [comment]
Yes it worked! Thank you!

By the way, in Android App I tried login in with Google, it didn't work. Just had a toast of code 10, message 10.

Let me know when you have finished implementing.

**Comment by tsnanh** [comment]
I'm using Firebase Auth and it requires SHA-1 added in my Firebase project :D. Send me SHA-1 or SHA-256 from Gradle signing report then I'll add it to my project.

**Comment by kimjiwongit** [comment]
99:02:8D:87:DB:38:1C:2F:0D:F3:FD:6B:29:AC:E4:56:68:B4:4D:14

Also, for what purpose are you using firebase-admin in server?

Also, I hope I am not interrupting you with comments.

**Comment by tsnanh** [comment]
No, you don't :D.
I have just added your SHA-1 to my project.
I use the Firebase admin SDK because I'm familiar with it and it's very easy to use. :D
